language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  - provider: npm
    on:
      tags: true
      all_branches: true
    email: cle.garnier@gmail.com
    api_key:
      secure: fVgLDT4Ag3BwTDA5rmlBtBurux6OejBnYMnNHye16Ng3i9ivEqpWPzVgVELHdhfe1YjXBfAzR4MtXUYpibOoaN2+c96+3Juq3ang0vl6ao6EtZyjXGrhaqgmuH3mSODmT1DFsCOuwD3rr+6dQZKgAjLCU0qh1wM5IDr0Wy7ls5i8wB0DmFvebJvZiDkOf2g5g5vonlCD0uKPqsEALwcv7U3rAW8izdKlP7wGZmerTd7gBEMz22zxrEnOtYZY3mwh3U3zSQXoR5IV1RRpD9fI5/orDWk668RrnKnKtwgr3Dh8xlyG8tR8RC7pgM6j2TyYwnplDdMTZG5HztYxBg3hVGCFM6M7NAAKohj8qDwrm1o9NeRqeZ8EOjhFnLJnCIHnf4jh7DL1q6es8EJSux5Ez+K956EPU3axwQzOrRfhXgI3+MeuGZ5P8dKFABF5RO9C2X2cnBNnN1tO42Kx5HuWNb/I2SOdTqOX8wo3Btdwl8a04Eb2WUWPUH4mvzo88SFXTiLAzrZi6P7f1CdQ6+vuyB/ftC7AV1s/BPoSGL8f+w64RHTHAbDjR9t4oChPoW9sQvczv3ICeqZj0253Q5khSO+NUuamI5Bss706fJp+1GjD4YihGkOEhpVCJT/QOIJyFqfJqpQQEmarAbaGO1dZda2Hz7voM64ZcSmUKs3hFC0=

script:
- npm test
